baseURL = "https://kmetallic04.github.io/"
locale = "en-us"
title = "Phantom Reads"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

pagination.pagerSize = 10

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  description = "Phantom Reads"
  author = "Kevin Maina"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false

  [params.label]
    text = "Phantom Reads"
    icon = "/img/logo.jpg"
    iconHeight = 32

  [params.profileMode]
    enabled = true
    title = "Phantom Reads"
    subtitle = "Hey, I’m Kevin! Code enthusiast, focused on data and platform infrastructure. I also love building financial products. Let's connect!"

    [[params.profileMode.buttons]]
      name = "Posts"
      url = "posts"

    [[params.profileMode.buttons]]
      name = "About"
      url = "about"

  [params.homeInfoParams]
    Title = "Phantom Reads"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/kmetallic04"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kevin-maina-4457347b"

  [[params.socialIcons]]
    name = "x"
    url = "https://twitter.com/Kevin_Metallic"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:wamburukmaina@gmail.com"

  [[params.socialIcons]]
    name = "rss"
    url = "index.xml"

  [params.assets]
    favicon = "/img/logo.jpg"
    favicon16x16 = "/img/logo.jpg"
    favicon32x32 = "/img/logo.jpg"
    apple_touch_icon = "/img/logo.jpg"
    disableHLJS = false

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "archives"
  name = "Archive"
  url = "/archives/"
  weight = 30

[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 40

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 50

[outputs]
  home = ["HTML", "RSS", "JSON"]
